apiVersion: v1
data:
  myFile: {{- .Values.configmap.myFile | toYaml | indent 1 }}
  myArray: |
  {{- range $k, $v := .Values.configmap.myArray }}
    - {{ . | toYaml | indent 4 | trim }}
  {{- end }}
kind: ConfigMap
metadata:
  name: nginx-version
  namespace: {{ .Values.namespace.name }}