apiVersion: v1
data:
  myFile: {{- .Values.configmap.myFile | toYaml | indent 1 }}
  myArray:
    {{ .Values.configmap.myArray | toYaml | indent 4 | trim }}
kind: ConfigMap
metadata:
  name: nginx-version
  namespace: {{ .Values.namespace.name }}