namespace:
  name: prod

service:
  port: 80
  type: ClusterIP

image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: 70m
    memory: 256Mi

configmap:
  myFile: |
    This is a multiline
    value, aka heredoc.
  myArray:
    key1: value1
    key2: value2
